Add missing elements to RunStatus enum
adeo/iwc-tfc-client pull request #8
Opened 2020-10-02 23:12 UTC by james-emerton

There were some elements missing which could cause a `ValidationError` while accessing the `status`.

I've copied the list from the Terraform API docs, in the same order as they appear there to make maintenance easy.

https://www.terraform.io/docs/cloud/api/run.html

2020-10-05 10:16 UTC, mvanholsteijn approved these changes
This is the list of states as defined by https://www.terraform.io/docs/cloud/api/run.html#run-states

2020-10-27 15:58 UTC, alex-ikse requested changes
Please sort RunStatus values.

2020-10-27 16:58 UTC, james-emerton commented
Hi @alex-ikse,

I've listed the enum values in the order they appear in the TFC documentation deliberately. I believe this makes the list easier to maintain, should additional elements be added over time.

2020-10-27 17:31 UTC, alex-ikse approved these changes
Hi @james-emerton 
It's a sensible point of view ;)
I accept your PR and will create a PR on the terraform documentation to sort the list :-D

2020-10-27 17:32 UTC, merged